import { GameInterface } from './GameInterface';

const DefaultGameState: GameInterface = {
  tacos: 0,
  perInterval: 0,
  ownsCapital: false,
  capital: [
    {
      index: 0,
      name: 'spatula',
      display: 'Spatula',
      cost: 10,
      owned: 0,
      increment: 0.01,
      priceFactor: 1.2,
      image: 'https://i.imgur.com/JHAtorH.png',
    }, {
      index: 1,
      name: 'tortilla press',
      display: 'Tortilla Press',
      cost: 50,
      owned: 0,
      increment: 0.08,
      priceFactor: 1.3,
      image: 'https://i.imgur.com/Ra2qj8t.jpg',
    },
    {
      index: 2,
      name: 'trompo',
      display: 'Trompo',
      cost: 200,
      owned: 0,
      increment: 0.18,
      priceFactor: 1.4,
      image: 'https://i.imgur.com/7MB9Yn6.jpg',
    },
    {
      index: 3,
      name: 'taco cart',
      display: 'Taco cart',
      cost: 750,
      owned: 0,
      increment: 0.24,
      priceFactor: 1.6,
      image: 'https://i.imgur.com/ToVd4wR.png',
    },
    {
      index: 4,
      name: 'food truck',
      display: 'Food Truck',
      cost: 1500,
      owned: 0,
      increment: 0.29,
      priceFactor: 1.8,
      image: 'https://i.imgur.com/WDJN7FS.png',
    },
    {
      index: 5,
      name: 'cantina',
      display: 'Cantina',
      cost: 5000,
      owned: 0,
      increment: 0.4,
      priceFactor: 1.8,
      image: 'https://i.imgur.com/nbWaWJ4.jpg',
    },
    {
      index: 6,
      name: 'restaurant',
      display: 'Restaurant',
      cost: 10000,
      owned: 0,
      increment: 1,
      priceFactor: 1.8,
      image: 'https://i.imgur.com/0Adp056.jpg',
    },
  ],
  upgrades: [
    {
      index: 0,
      name: 'Double stand production',
      cost: 20,
      isOwned: false,
      metThreshold: false,
      targetCapitalIndex: 0,
      impactFactor: 2,
      displayThreshold: 10,
    }, {
      index: 1,
      name: 'Double stand production 2',
      cost: 120,
      isOwned: false,
      metThreshold: false,
      targetCapitalIndex: 0,
      impactFactor: 2,
      displayThreshold: 100,
    }, {
      index: 2,
      name: 'Double stand production 3',
      cost: 250,
      isOwned: false,
      metThreshold: false,
      targetCapitalIndex: 0,
      impactFactor: 2,
      displayThreshold: 150,
    },
  ],
};

export default DefaultGameState;
